.gitignore
README.md
docs/Manual-benchmark.md
requirements.txt
src/common/metrics.py
src/scripts/generate_data/generate.py
src/scripts/lightgbm_cli/score.py
src/scripts/lightgbm_python/score.py
src/scripts/lightgbm_python/train.py

This PR creates a very first set of scripts that one can run manually to test training and inferencing for lightgbm, both with Python API and CLI.
It provides some utility classes for measuring wall time.
Apologies for the size of this PR, this is for creating some foundations to build on top of in next round of PRs.

First batch of manual scripts for local testing of lightgbm python + cli

---

.github/workflows/benchmark_scripts.yml
src/common/metrics.py
tests/conftest.py
tests/scripts/test_generate_data.py

Create basic workflow

---

docs/Benchmark-project.md

This is a write-up of the main proposal, implementation goals, general methodology and milestones.
This is in relation with 2 more PRs, separated to facilitate review:
-  #8 
- #9

Docs: benchmark goals and methodology

---

src/scripts/lightgbm_python/score.py
src/scripts/lightgbm_python/train.py

register logger in lightgbm

---

.github/workflows/azureml_pipelines.yml
pipelines/azureml/pipelines/lightgbm_inferencing.py
requirements.txt
src/scripts/lightgbm_python/lightgbm_custom.dockerfile

This PR creates a github workflow that validates the AzureML pipelines.
Currently employed only for inferencing.
Fix: the lightgbm custom dockerfile was missing, glad this build caught that issue :P

Create azureml_pipelines.yml workflow

---

pipelines/azureml/conf/experiments/lightgbm_training/cpu.yaml
pipelines/azureml/pipelines/lightgbm_training.py

- added options in config file to set name of outputs
- register outputs in lightgbm training

Auto-register outputs of data generation and training

---

pipelines/azureml/conf/experiments/benchmark-inferencing.yaml
src/scripts/analysis/analyze.py
src/scripts/analysis/templates/inferencing.md
src/scripts/lightgbm_python/score.py
src/scripts/treelite_python/score.py

- Comment the analysis script much more
- Align the notion of "config" with tasks from yaml config files

Better reporting script

---

pipelines/azureml/conf/experiments/benchmarks/training-cpu-vs-gpu.yaml
pipelines/azureml/conf/experiments/lightgbm_training/cpu-custom.yaml
pipelines/azureml/conf/experiments/lightgbm_training/cpu.yaml
pipelines/azureml/conf/experiments/lightgbm_training/gpu.yaml
pipelines/azureml/conf/experiments/lightgbm_training/sweep.yaml
pipelines/azureml/pipelines/lightgbm_training.py
src/common/tasks.py

- add a "task_key" to all tasks (data generation, training, inferencing)
- use task_key to create model basename in pipeline
- implement model basename + auto registration of model as dataset
- add some custom properties, in particular variant_index

Implement training model registration

---

pipelines/azureml/pipelines/lightgbm_training.py
src/common/tasks.py
src/scripts/lightgbm_python/train.py
src/scripts/lightgbm_python/train_spec.yaml

- set header as non required
- add construct parameter to choose to pre-construct dataset or not
- connect verbose to a config in yaml

Update parameters in lightgbm train (header, construct, verbose)

---

src/scripts/lightgbm_python/train.py

Comment the lines trying to log "n/a".

MLflow does not accep string as value.

---

.github/workflows/azureml_pipelines.yml

Temporary fix to avoid the incompatibility between azure cli token credential cache and Azure SDK.

Hotfix azure cli to unblock login in build

---

docker/lightgbm-custom/v321_patch_cpu_mpi_build.dockerfile
docker/lightgbm-custom/v330_patch_cpu_mpi_build.dockerfile
docker/lightgbm-v3.2.1/linux_cpu_mpi_build.dockerfile
docker/lightgbm-v3.2.1/linux_cpu_mpi_pip.dockerfile
docker/lightgbm-v3.3.0/linux_cpu_mpi_build.dockerfile
docker/lightgbm-v3.3.0/linux_cpu_mpi_pip.dockerfile
requirements.txt
src/common/metrics.py
src/scripts/inferencing/lightgbm_c_api/score.py

This PR just provides more metrics for inferencing:
- we added p75 and p95
- we now log a histogram of the latencies in mlflow

Add more percentile metrics and log a histogram plot

---

src/scripts/inferencing/lightgbm_c_api/spec.yaml
src/scripts/inferencing/lightgbm_python/spec.yaml

Add outputs to components specs for lightgbm

---

src/scripts/inferencing/lightgbm_c_api/score.py

The argument `output_result` only works when using LightGBM CPI, and not the API.
We're using numpy instead then.

Use numpy to store outputs in the C API lightgbm inferencing module

---

tests/common/test_component.py

Extending coverage of our unit tests by creating generic tests for RunningScript helper class.

Create unit tests for component class

---

.github/workflows/benchmark_scripts.yml

This PR adds a code coverage summary in the PR.

Update build to integrate code coverage

---

.github/workflows/azureml_pipelines.yml
.github/workflows/benchmark_scripts.yml
.github/workflows/docker_images.yml

Allow contributors to trigger github actions manually using https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

Make github actions manually triggered

---

README.md

Add two action status badges

---

.github/workflows/docs.yml

This implement #227 for the docs build.

HotFix: specify pip version that works for our build [docs build]

---

src/common/components.py
src/common/ray.py

- split RunnableScript.main() into submethods
- create "run hook" that can be overridden in script specific implementations
- RayScript: implement ray-specific run hook and remove custom main method

Create unified main() function for all components

---

src/common/components.py
src/common/distributed.py
src/scripts/analysis/analyze.py
src/scripts/data_processing/generate_data/generate.py
src/scripts/data_processing/lightgbm_data2bin/data2bin.py
src/scripts/data_processing/partition_data/partition.py
src/scripts/inferencing/custom_win_cli/score.py
src/scripts/inferencing/lightgbm_c_api/score.py
src/scripts/inferencing/lightgbm_python/score.py
src/scripts/inferencing/lightgbm_ray/score.py
src/scripts/inferencing/treelite_python/score.py
src/scripts/model_transformation/treelite_compile/compile_treelite.py
src/scripts/sample/sample.py
src/scripts/training/lightgbm_python/train.py
src/scripts/training/lightgbm_ray/train.py

When you'll run a script locally, you'll know exactly from which class each of the script argument come from.

add path to module + class name to each arg parser help

---

src/pipelines/azureml/lightgbm_training.py

add construct to training_params.

---

src/common/pipelines.py

convert dictconfig to dict.

---

src/scripts/training/lightgbm_python/spec.yaml
src/scripts/training/lightgbm_python/train.py
src/scripts/training/lightgbm_ray/train.py
tests/scripts/test_lightgbm_python.py
tests/scripts/test_training_lightgbm_ray.py

* Added `model_filename` param to the train module. Currently, the model is saved as `model.txt`

Added model_filename param to train module

---

conf/experiments/data-generation.yaml
requirements.txt

Few dependencies were pinned to fix the build pipeline.

fix pipeline

---

src/scripts/training/lightgbm_python/spec.yaml
src/scripts/training/lightgbm_python/train.py

This PR allows user to provide lightgbm model file as an input to the component. The component will continue the training on the input model. 
Continuous training has been tested with freeforms and distributed training.

continuous training
