microsoft/lightgbm-benchmark

.gitignore, requirements.txt, src/common/metrics.py, src/scripts/generate_data/generate.py, src/scripts/lightgbm_python/score.py, src/scripts/lightgbm_python/train.py, tests/common/test_metrics.py
This PR implements an mlflow metrics logger as a utility class. This class is a singleton to ensure mlflow initialization happens only once. It provides methods for user scripts to log metrics without taking care of mlflow backend.
This class is then used accross existing manual scripts.
=> Implement mlflow metrics logging in utility class, use accross manual scripts

src/scripts/lightgbm_cli/score.py, src/scripts/lightgbm_python/score.py
Instead of using numpy to load inputs, use lightgbm Dataset to construct the raw_data before calling predict.
this allows support of the file formats supported by lightgbm, ex libsvm, not just plain csv.
=> allow for libsvm format in score python

docs/Install.md, docs/Manual-benchmark.md
So that we can expand the instructions with local dependencies if necessary.
=> put install docs in distinct markdown

src/scripts/treelite_python/score.py, tests/scripts/test_treelite_python.py
Align the script from treelite_python/score.py to the "developer guide" sample.py (with all its goodness).
Created a unit test (just trying to run with some arguments) to validate treelite script.
NOTE: still lots of duplicate code, will work on factoring it later.
See developer guide in the docs https://github.com/microsoft/lightgbm-benchmark/blob/main/docs/Developer-guide.md
=> align treelite to sample and add unit tests

src/scripts/lightgbm_cli/score.py
As described in Issue #33, passing arguments to `subprocess.run` as a string yields platform-dependent behavior. In this particular case, `src/scripts/lightgbm_cli/score.py` crashed when running in Linux. 
This PR updates _args_ to be consumed as a list, which is correctly interpreted by all platforms. 
Closes #33
=> Updating subprocess.run to consume arguments as a list instead of a string

docs/contribute/reporting-guide.md, docs/quickstart/manual-benchmark.md, mkdocs.yml
I just reviewed the manual instructions to ensure they were still working considering the latest changes in the script arguments. They do :)
Used the opportunity to revise the docs engine and add code blocks as panels whenever there's 2 languages involved :)
This is what it will look like:
=> Check manual docs for consistency with script arguments, add code blocks as panels

pipelines/azureml/conf/modules/benchmark.yaml, pipelines/azureml/pipelines/lightgbm_e2e_synthetic.py
The usual line calling apply_smart_runsettings() was missing in 2 of the modules of e2e pipeline. It was running on the default compute.
=> Fix: add runsettings everywhere

src/common/lightgbm.py, src/common/metrics.py, src/scripts/lightgbm_python/train.py, tests/common/test_metrics.py
This uses lightgbm callbacks to record training metrics in mlflow.
This shows up in AzureML nicely.
=> implement callbacks to capture lightgbm metrics

src/common/lightgbm.py, src/common/metrics.py, tests/common/test_metrics.py
The goal is to introduce a prefix for all calls to mlflow.log_metric(). This will be useful in the mpi scenario where we want to add the node number in front of our metrics.
callbacks had this node_index parameter, this is now redundant if we set prefix in metrics_logger directly, so node_index has been removed.
=> Implement optional prefix to metrics in MetricsLogger

src/scripts/lightgbm_python/dockers/lightgbm_cpu_mpi_build.dockerfile
In order to establish fair comparison, we want to run lightgbm from a classic compilation (not just pypi).
This implement the dockerfile for that, which can be used by using override_docker in the conf file of the experiment.
=> Add dockerfile to run from manual build (use as baseline)

pipelines/azureml/conf/experiments/data-generation.yaml, pipelines/azureml/pipelines/data_generation.py, src/common/data.py
- implement a config for the data generation "task" (dataclass)
- change data generation config to use this task as a list
- update pipeline so that build() provides a generic data generation pipeline, and pipeline_instance() extends the pipeline as much as needed to complete all the tasks
=> Enable data generation pipeline to generate multiple datasets in one run

src/common/io.py, src/scripts/partition_data/partition.py
In previous code, we were limiting the inputs of partition.py to be one single file. But the code already supported having multiple input files (to re-partition them).
This simple fix allows that to be possible now.
=> allow partition script to re-partition data

src/common/sweep.py, tests/common/test_sweep.py
Initial sweep argument parser did not automatically construct its own internal list of parsing functions (used a static list instead, due to an overlook).
In this PR, we added some logging, and constructed the list of parsing functions depending on the allowed sweep params list.
=> fix sweep parser implementation

.github/workflows/docker_images.yml, docker/lightgbm-custom/v321_patch_cpu_mpi_build.dockerfile, docker/lightgbm-v3.2.1/linux_cpu_mpi_build.dockerfile, docker/lightgbm-v3.2.1/linux_cpu_mpi_pip.dockerfile, docker/lightgbm-v3.2.1/linux_cuda_build.dockerfile, docker/lightgbm-v3.2.1/linux_gpu_build.dockerfile, docker/lightgbm-v3.2.1/linux_gpu_pip.dockerfile, docker/lightgbm-v3.2.1/windows_cpu_pip.dockerfile, docker/lightgbm-v3.3.0/linux_cpu_mpi_build.dockerfile, docker/lightgbm-v3.3.0/linux_cpu_mpi_pip.dockerfile, docker/lightgbm-v3.3.0/windows_cpu_pip.dockerfile
- in docker build, use ARG to make sure we're building from the github branch of the PR (we didn't do that before, so we actually only built from main branch)
- standardize ARG for every dockerfile
=> Use arguments in docker files in order to build from PR properly

src/binaries/lightgbm_predict/main.cc
Running on libsvm files on local/windows VM was working perfectly. But on Linux in AzureML was failing due to the fatal error here: ["Log::Fatal("Input format error when parsing as LibSVM")"](https://github.com/microsoft/LightGBM/blob/3b6ebd794b82e02f8d5e1d0b915533bb4c36dbfc/src/io/parser.hpp#L118).
Turns out, the process for parsing libsvm files and use LibSVMParser.ParseOneLine() was failing in Linux (and not on my local tests on Windows) because the trimming behavior of getline() is different between GCC and MSVC. This PR resolves that by trimming lines ourselves.
=> Fix exceptions that occured when parsing libsvm input files in lightgbm_predict binary on Linux

pipelines/azureml/conf/experiments/lightgbm_training/cpu-custom.yaml, pipelines/azureml/conf/experiments/lightgbm_training/gpu.yaml, pipelines/azureml/conf/experiments/lightgbm_training/sweep.yaml, pipelines/azureml/pipelines/lightgbm_training.py
The lightgbm training pipeline wasn't updated with the latest path to the dockers (that change was made in inferencing pipeline, but not propagated to training). This PR fixes that.
=> Fix path to custom docker containers for LightGBM training pipeline

src/common/components.py
This PR fixes the order of initialization of mlflow. It will now be done AFTER argument parsing, to avoid logging any mlflow metrics if we just run the script locally with `-h` option.
=> Fix order of initialization between argparse and mlflow

src/scripts/inferencing/lightgbm_python/score.py, tests/scripts/test_lightgbm_python.py
We need to check if the outputs from lightgbm are consistent accross variants. This will output the predictions.
=> Add predictions output to LightGBM python

requirements.txt, src/scripts/inferencing/treelite_python/conda_env.yaml, src/scripts/model_transformation/treelite_compile/conda_env.yaml
Update dependencies to use treelite 2.1.0 instead of 1.3.0
=> Update to treelite 2.1.0, and other dependencies updates

src/common/math.py, tests/common/test_math.py
This will help with inferencing benchmark and others, where the runs produce fluctuating values for the percentiles.
This adressed #162 partially, we'd still need to inject that in the inference metrics and in the report (we'll do once #177 is merged)
=> Implement a bootstrap confidence interval method

requirements.txt, src/scripts/data_processing/generate_data/conda_env.yaml, src/scripts/data_processing/lightgbm_data2bin/conda_env.yml, src/scripts/data_processing/partition_data/conda_env.yml, src/scripts/inferencing/treelite_python/conda_env.yaml, src/scripts/model_transformation/treelite_compile/conda_env.yaml, src/scripts/sample/conda_env.yaml
Since we merged #178 we now use psutil in the common metrics class. This dependency was forgotten in the modules conda environments. This PR fixes that. It also updates some of those dependencies.
=> Fix conda dependencies to add common required package psutil

docs/run/manual-benchmark.md, src/scripts/training/lightgbm_python/train.py
Verified the manual benchmark docs page and fixed the following:
- made device_type optional when running local
- explained device_type in the docs
- added num_thread as it could be relevant for lightgbm inferencing
- removed the lightgbm_cli section as we're trying to deprecate this (see #165
=> verify arguments of manual benchmark and align with scripts

src/common/metrics.py, src/scripts/inferencing/lightgbm_c_api/score.py, src/scripts/inferencing/lightgbm_python/score.py, tests/common/test_metrics.py
This PR creates a helper function to provide latency metrics with a unified format.
It also opens the door for injecting confidence intervals later without modifying all modules (see #179 ).
=> Unify latency metrics inside a helper function

src/common/components.py, src/common/perf.py, tests/common/test_perf.py
This creates a performance measurement thread to capture cpu/mem utilization and other perf related metrics.
The thread is disconnected from the other code from now, but will be built upon in distributed training.
=> Create performance reporting thread for single node components

src/common/components.py, src/common/distributed.py, src/scripts/training/lightgbm_python/train.py
This PR introduces a new component class `MultiNodeScript` that is distinct from `RunnableScript`.
Initially, every component was using `RunnableScript`, but for distributed we needed to bypass some of the initializing code (you want to log properties only on head node, etc), using a flag. This is confusing, and also we're already thinking of adding extensions to the distributed lightgbm training (like performance metrics #71 ) which will require even more differences between single node and multi node.
Introducing this new class makes developer code simpler (just import the right class), and refactors some common routines.
=> Create distinct class for single node and multi node, with shared utility functions

src/common/components.py, src/common/distributed.py, src/common/metrics.py, tests/common/test_metrics.py
This PR removes the mechanism establishing MetricsLogger as a Singleton. This was introduces in the beginning to support recording metrics from all over the place, but this is now deprecated since we have clean components classes.
Also, this introduces metric types that are not required, but will be helpful for integrating performance metrics and distributed metrics.
=> Remove singleton from MetricsLogger

src/common/perf.py, tests/common/test_perf.py
This PR implements a "collector" on top of the perf measurement thread, that keeps receiving perf reports from the thread, but will keep only a maximum number of reports per run. Every time maximum is reached, the collector will filter out values and start skipping reports.
=> Add a perf metric collector to ensure number of measures stays under control

.github/workflows/docker_images.yml, src/scripts/inferencing/lightgbm_python/default.dockerfile
This PR changes the github action that tests all dockerfiles so that we can also test `default.dockerfile` located within the `src/scripts/` tree.
It also updated one such dockerfile just for testing the build.
=> Use github action to test all dockerfiles in script directories (defaults)

src/common/components.py, tests/common/test_component.py
This PR implements a try/except around run method in component helper class. There reason is, now that we have perf metrics produced by threads, we want to avoid the job to hang if the run function breaks. We still raise the exception so it shows in AzureML.
=> add try/except around component run

src/common/components.py, tests/scripts/test_inferencing_custom_win_cli.py, tests/scripts/test_lightgbm_inferencing_c_api.py
Increase code coverage by creating unit tests for 2 inferencing scripts that rely on using binaries.
This mocks the call to subprocess, and checks only superficial aspects (metrics).
=> Implement unit tests for inferencing scripts using binaries

src/common/components.py, src/common/distributed.py, tests/common/test_component.py, tests/common/test_distributed.py, tests/scripts/test_lightgbm_python.py
This PR makes it possible to unit test distributed component (see issue #196) by containing MPI initialization inside a specific class (`MPIHandler`) and patching it during the unit tests.
Changes:
- in common.distributed: creation of `MPIHandler` to handle all calls to MPI library
- in tests.common.test_component: separate functions to test properties and metrics, so we can reuse in testing distributed component
- in tests.common: add test_distributed to test MultiNodeScript (both success and failure)
=> Implement tests on MultiNodeScript class by separating mpi initialization

.gitignore, src/common/distributed.py, src/scripts/training/lightgbm_python/default.dockerfile, tests/common/test_distributed.py
The initialization of MPI in python might interact with the initialization done by the framework themselves (ex: lighgbm training). We might still need it in some scenarios (sharing distributed metrics like in #185), so we're making this optional for now.
When mpi_init_node is left to None, we use OMPI env variables to discover how many nodes there are, and create the right configuration for the distributed script to use.
We're also proposing to upgrade to openmpi4.
NOTE: this is part of an effort to try this distributed training on production scenarios where we're hitting internal mpi exceptions (MPI_ERR_TRUNCATE).
=> Make MPI initialization optional and use OMPI env vars for world discovery

requirements.txt, src/pipelines/azureml/data_generation.py
This PR just upgrades requirements to use latest shrike and azure-ml-component sdks.
hydra-core has been downgraded to match with shrike requirements.
We're also adding tags to generated datasets, as a new feature of component sdk.
=> Upgrade to latest shrike+azuremlsdk, add tags to datasets

requirements.txt, src/common/data.py, src/common/tasks.py, src/pipelines/azureml/data_generation.py, src/scripts/data_processing/generate_data/generate.py, src/scripts/data_processing/generate_data/spec.yaml, tests/common/test_data.py, tests/scripts/test_generate_data.py
This implements a synthetic data generator not constrained by the memory limit (but still constrained by disk).
This works by creating a synthetic data generator that can produce batches of random data. This generator is being iterated on to create the required amount of data for training, testing and inferencing and append all batched sequentially.
This is still limited by disk allocation for now.
=> Generate bigger synthetic data using per-batch generation [regression only]

.github/workflows/codeql-analysis.yml, docs/run/azureml/designer-ui.md
The page on designer ui didn't show images because they used `/` as absolute path. This PR fixes that.
=> Fix docs on Designer UI by using rel paths

src/common/components.py, src/common/pipelines.py
To make submission more user friendly, this PR adds a warning that pipeline is not submitted by default. It also, shows the portal url clearly in the logs.
=> Add url after submit, and show warning to add +run.submit=true

src/common/aml.py, src/pipelines/azureml/data_generation.py, src/pipelines/azureml/lightgbm_inferencing.py, src/pipelines/azureml/lightgbm_training.py, tests/common/test_aml.py
This PR uses component sdk to enforce a readable display name for all the runs for training and inferencing.
This code will add a programmatically generated `node_name` for the steps of our pipelines. This node name is filtered out to avoid breaking naming conventions in AzureML (`filter_run_name` method).
=> Add readable "display name" for each step

src/common/metrics.py, tests/common/test_metrics.py
These methods will let us record files (in particular, ray timeline, or models) in the mlflow session.
=> Implement log_artifact methods in metrics logger

.github/workflows/azureml_pipelines.yml, .github/workflows/benchmark_scripts.yml
Our build currently fails for some dependencies issues. This has happened only after upgrading to latest pip==22.0, this PR fixes the version that was working before.
=> HotFix: specify pip version that works for our build

src/common/pipelines.py
In the call to `azureml_connect()`, I forgot to add `force` as a parameter. This is important as it allows to switch between tenants more easily (set `aml.force:True` to force tenant re-auth).
=> Add force param to azureml_connect call to allow for tenant switch

src/common/ray.py
This PR adds fixes to the RayScript class used to run ray components (lightgbm ray inferencing + coming soon lightgbm ray training).
This also adds all the required parameters/properties that were not initially implemented in this class, and that are required for the benchmark analysis script to run.
Finally, it fixes `available_nodes` in RayScript, which wasn't initialized properly, and was failing when running component in distributed mode.
NOTE: this PR was extracted out of the general lightgbm-ray pr #223 .
=> Add perf reporting to RayScript class

src/common/components.py, src/common/distributed.py, src/common/metrics.py, tests/common/test_metrics.py
For prod environment where mlflow would not work due to compliance requirements, AzureML Run log methods could still be applied.
This PR re-implements the `MetricsLogger` class to use AzureML Run instead of MLFlow, with a parameter switch to instantiate the right "driver".
=> Implement classic AzureML log reporting class (as backup)

src/common/ray.py
After merge of #228, the RayScript was not reporting metrics because it was still initializing MetricsLogger and not the right metric driver (mlflow/azureml).
This PR fixes that.
=> [fix] add metrics driver initialization in RayScript

src/common/distributed.py
The member variable `._comm` in MultiNodeMPIDriver wasn't initialized properly in initialize() method. This was overlooked at this is not used anywhere else in the code.
This is fixed in this PR.
=> [Fix] align name of internal _comm variable in MultiNodeMPIDriver

.github/workflows/benchmark_scripts.yml
Fix CI by pinning protobuf version to `3.19.4`
Affected PR: https://github.com/microsoft/lightgbm-benchmark/pull/265111
=> Fix CI by pinning protobuf

src/scripts/training/lightgbm_python/train.py
param `parser_config_file` was (incorrectly) passing the folder path but `lightgbm-transform` expects a filename. In such case `lightgbm-transform` doesn't compliant about it and ignore the parameter.
=> Fix input parameter `parser_config_file` to support lightgbm-transform
